[book]
title = "nix-pklx Documentation"
authors = ["caniko"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
site-url = "/nix-pklx/"
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/caniko/nix-pklx"
